const mongoose = require('mongoose')
  const bd =new mongoose.Schema({
    TOURNAMENT_ID:{
      type:String,
      default:"123456"
    },
    TOURNAMENT_NAME:{
      type:String,
    },
    STATUS:{
      type:Boolean,
      default:true,
    },
    LOCATION:{
      type:String,
    },
    CITY:{
      type:String
    },
    ADDRESS:{
      type:String
    },
    TYPE:{
      type:String,
      default:"DYNAMIC",
    },
    START_DATE:{
      type:String
    },
    COLOR:{
      type:String
    },
    END_DATE:{
      type:String
    },
    REGISTRATION_CLOSES_BEFORE:{
      type:Number,
      default:6 
    },
    START_TIME:{
      type:String
    },
    END_TIME:{
      type:String
    },
    SPORT:{
      type:String,    //drop down
    },
    CANCELLATION_STATUS:{
      type:Boolean,
      default:false,
    },
    CATEGORY:{
      type:String,
     //drop down
    },
    MATCHES:{  //array of match ids
      type:[String]
    },
    NO_OF_COURTS:{
      type:Number
    },
    BREAK_TIME:{
      type:String
    },
    PARTICIPANTS:{
      type:[String],
   // Array of participants
    },
    NO_OF_KNOCKOUT_ROUNDS:{
      type:Number
    },
    SPOT_STATUS_ARRAY:{
      type:[String],
      default:[]
    },
    GOLD:{
      type:Number
    },
    SILVER:{
      type:Number
    },
    BRONZE:{
      type:Number
    },
    PRIZE_POOL:{
      type:Number,
      default:0
    },
    AGE_CATEGORY:{
      type:String
    },
    ENTRY_FEE:{
      type:Number,
      default:0    
    },
    IMG_URL:{
      type:String
    },
    START_TIMESTAMP:{
      type:String
    },
    END_TIMESTAMP:{
      type:String
    },
    ORGANIZER_NAME:{
      type:String
    },
    ORGANIZER_ID:{
      type:String
    }
})
module.exports = mongoose.model('tourneys',bd)